/*
===========================================================
E-COMMERCE BUSINESS ANALYTICS
05 - RFM CUSTOMER SEGMENTATION
===========================================================

Purpose:
Segment customers based on:

R = Recency
F = Frequency
M = Monetary Value

Reference Date:
2026-01-01

Scope:
Only completed orders are included.

Note:
The final Power BI dashboard uses the Python-generated
customer_rfm.csv, where ties were explicitly handled
before quintile assignment.

This SQL implementation demonstrates the same analytical
RFM methodology using PostgreSQL window functions.
*/


-- =========================================================
-- 1. BUILD CUSTOMER RFM BASE
-- =========================================================

WITH rfm_base AS (

    SELECT
        o.customer_id,

        DATE '2026-01-01'
        - MAX(o.order_date)::date
        AS recency,

        COUNT(
            DISTINCT o.order_id
        ) AS frequency,

        SUM(
            oi.revenue
        ) AS monetary

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE
        o.order_status = 'Completed'

    GROUP BY
        o.customer_id
)

SELECT
    customer_id,
    recency,
    frequency,

    ROUND(
        monetary::numeric,
        2
    ) AS monetary

FROM rfm_base

ORDER BY
    monetary DESC;


/*
Definitions:

Recency:
Number of days between the reference date and
the customer's most recent completed order.

Frequency:
Number of completed orders made by the customer.

Monetary:
Total revenue generated by the customer.
*/


-- =========================================================
-- 2. ASSIGN RFM QUINTILE SCORES
-- =========================================================

WITH rfm_base AS (

    SELECT
        o.customer_id,

        DATE '2026-01-01'
        - MAX(o.order_date)::date
        AS recency,

        COUNT(
            DISTINCT o.order_id
        ) AS frequency,

        SUM(
            oi.revenue
        ) AS monetary

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE
        o.order_status = 'Completed'

    GROUP BY
        o.customer_id
),

rfm_scored AS (

    SELECT
        customer_id,
        recency,
        frequency,
        monetary,

        /*
        Lower recency is better.

        NTILE assigns 1 to the most recent group,
        so the result is reversed to create a
        5 = best scoring system.
        */

        6 - NTILE(5) OVER (
            ORDER BY recency ASC
        ) AS r_score,


        /*
        Higher frequency is better.
        */

        NTILE(5) OVER (
            ORDER BY frequency ASC
        ) AS f_score,


        /*
        Higher monetary value is better.
        */

        NTILE(5) OVER (
            ORDER BY monetary ASC
        ) AS m_score

    FROM rfm_base
)

SELECT
    customer_id,
    recency,
    frequency,

    ROUND(
        monetary::numeric,
        2
    ) AS monetary,

    r_score,
    f_score,
    m_score

FROM rfm_scored

ORDER BY
    monetary DESC;


/*
Each customer receives a score from 1 to 5.

Higher score = stronger performance.

Example:

R = 5 → purchased recently
F = 5 → purchases frequently
M = 5 → high customer value
*/


-- =========================================================
-- 3. CREATE CUSTOMER SEGMENTS
-- =========================================================

WITH rfm_base AS (

    SELECT
        o.customer_id,

        DATE '2026-01-01'
        - MAX(o.order_date)::date
        AS recency,

        COUNT(
            DISTINCT o.order_id
        ) AS frequency,

        SUM(
            oi.revenue
        ) AS monetary

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE
        o.order_status = 'Completed'

    GROUP BY
        o.customer_id
),

rfm_scored AS (

    SELECT
        customer_id,
        recency,
        frequency,
        monetary,

        6 - NTILE(5) OVER (
            ORDER BY recency ASC
        ) AS r_score,

        NTILE(5) OVER (
            ORDER BY frequency ASC
        ) AS f_score,

        NTILE(5) OVER (
            ORDER BY monetary ASC
        ) AS m_score

    FROM rfm_base
),

rfm_segmented AS (

    SELECT
        *,

        CASE

            WHEN
                r_score >= 4
                AND f_score >= 4
                AND m_score >= 4
            THEN 'Champions'


            WHEN
                f_score >= 4
                AND m_score >= 3
            THEN 'Loyal'


            WHEN
                r_score >= 4
                AND f_score <= 3
            THEN 'Potential Loyalists'


            WHEN
                r_score <= 2
                AND f_score >= 3
                AND m_score >= 3
            THEN 'At Risk'


            WHEN
                r_score <= 2
                AND f_score <= 2
            THEN 'Lost'


            ELSE 'Others'

        END AS rfm_segment

    FROM rfm_scored
)

SELECT
    customer_id,
    recency,
    frequency,

    ROUND(
        monetary::numeric,
        2
    ) AS monetary,

    r_score,
    f_score,
    m_score,
    rfm_segment

FROM rfm_segmented

ORDER BY
    monetary DESC;


-- =========================================================
-- 4. RFM SEGMENT PERFORMANCE
-- =========================================================

WITH rfm_base AS (

    SELECT
        o.customer_id,

        DATE '2026-01-01'
        - MAX(o.order_date)::date
        AS recency,

        COUNT(
            DISTINCT o.order_id
        ) AS frequency,

        SUM(
            oi.revenue
        ) AS monetary

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE
        o.order_status = 'Completed'

    GROUP BY
        o.customer_id
),

rfm_scored AS (

    SELECT
        *,

        6 - NTILE(5) OVER (
            ORDER BY recency ASC
        ) AS r_score,

        NTILE(5) OVER (
            ORDER BY frequency ASC
        ) AS f_score,

        NTILE(5) OVER (
            ORDER BY monetary ASC
        ) AS m_score

    FROM rfm_base
),

rfm_segmented AS (

    SELECT
        *,

        CASE

            WHEN
                r_score >= 4
                AND f_score >= 4
                AND m_score >= 4
            THEN 'Champions'

            WHEN
                f_score >= 4
                AND m_score >= 3
            THEN 'Loyal'

            WHEN
                r_score >= 4
                AND f_score <= 3
            THEN 'Potential Loyalists'

            WHEN
                r_score <= 2
                AND f_score >= 3
                AND m_score >= 3
            THEN 'At Risk'

            WHEN
                r_score <= 2
                AND f_score <= 2
            THEN 'Lost'

            ELSE 'Others'

        END AS rfm_segment

    FROM rfm_scored
)

SELECT
    rfm_segment,

    COUNT(*) AS customers,

    ROUND(
        SUM(monetary)::numeric,
        2
    ) AS segment_revenue,

    ROUND(
        AVG(monetary)::numeric,
        2
    ) AS average_customer_value,

    ROUND(
        AVG(frequency)::numeric,
        2
    ) AS average_purchase_frequency,

    ROUND(
        AVG(recency)::numeric,
        2
    ) AS average_recency_days

FROM rfm_segmented

GROUP BY
    rfm_segment

ORDER BY
    segment_revenue DESC;


/*
===========================================================
FINAL DASHBOARD RFM RESULTS
===========================================================

The final Power BI dashboard uses customer_rfm.csv
generated in Python.

Final customer counts:

Champions             : 2,340
Loyal                 : 1,293
Others                : 2,487
Potential Loyalists   : 1,652
At Risk               :   594
Lost                  : 2,913

Total                 : 11,279 customers


Final segment revenue:

Champions             : ~10.13M
Loyal                 : ~2.96M
Others                : ~2.20M
Lost                  : ~1.56M
Potential Loyalists   : ~1.42M
At Risk               : ~1.33M

Important:

Exact SQL NTILE results may differ slightly from the
final Python segmentation because the Python workflow
uses explicit tie handling before quintile assignment.

For dashboard reporting, customer_rfm.csv is treated
as the authoritative segmentation output.
*/


-- =========================================================
-- 5. SEGMENT REVENUE CONTRIBUTION
-- =========================================================

/*
For exact portfolio/dashboard segment contribution,
use the Python-generated customer_rfm.csv.

Champions contribute approximately half of total
customer revenue, demonstrating substantial value
concentration within the highest-value segment.

The At Risk segment also represents meaningful
historical revenue, making it relevant for retention
analysis.
*/


/*
===========================================================
BUSINESS INTERPRETATION

Champions
---------
Recent, frequent and high-value customers.
Priority: retention, loyalty and premium engagement.


Loyal
-----
Frequent and valuable customers.
Priority: strengthen loyalty and cross-sell.


Potential Loyalists
-------------------
Recent customers with potential to become more valuable.
Priority: encourage additional purchases.


At Risk
-------
Historically valuable customers who have not purchased
recently.
Priority: targeted reactivation and retention.


Lost
----
Low-frequency customers with long periods of inactivity.
Priority: selective reactivation based on expected value.


Others
------
Customers who do not meet the defined strategic
segment rules.


===========================================================
KEY BUSINESS TAKEAWAYS

1. Customer value is highly concentrated.

2. Champions represent a particularly important revenue
   segment and should receive strong retention attention.

3. At Risk customers previously generated meaningful
   revenue and represent a reactivation opportunity.

4. RFM enables customer strategy to move beyond broad
   one-size-fits-all marketing.

5. Segment-specific retention and engagement strategies
   can be designed based on recency, frequency and value.

===========================================================
*/